name: flutter_ujikom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  hexcolor: ^3.0.1
  lottie: ^2.2.0
  google_fonts: ^4.0.3
  get_storage: ^2.0.3
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
  - assets/images/
  - assets/lotties/

